### PR TITLE
fix(exclude-config): Use defaultExcludes for anything that isn't an array

### PR DESCRIPTION
**Pull request by JaKXz**
Tweaks on #11 and #12.

Thought of this in the discussion on https://github.com/istanbuljs/nyc/pull/366 - it's an easy edge case to cover.

### CODE REVIEW

**Comment by bcoe** [comment]
@JaKXz as I read this, the goal of this is to defend folks from accidentally providing invalid exclude configuration? e.g., providing an object instead of an array.

**Comment by JaKXz** [comment]
@bcoe yep! until we have a better idea for supporting a `"exclude": "{fancy: 'object'}"` configuration

**Comment by JaKXz** [comment]
Any thoughts on this @bcoe?

**Comment by bcoe** [comment]
@JaKXz 👍

**Pull request merged**
